In [1]:
import numpy as np
import matplotlib.pyplot as plt
from few.amplitude.ampinterp2d import  AmpInterpKerrEccEq_nex, AmpInterp2D, AmpInterpKerrEccEqv2, AmpInterpKerrEccEq
from few.utils.baseclasses import KerrEccentricEquatorial_nex, BackendLike, ModeIndicesLMBase
from few.amplitude.base import AmplitudeBase
import os
import pathlib
from copy import deepcopy
from typing import List, Optional, Union
import h5py
from few import get_file_manager

In [2]:

filename = (
    "ZNAmps_l10_m10_n92__extremal.h5" 
)


file_path = get_file_manager().get_file(filename)

with h5py.File(file_path, "r") as f:
    mode_indices = f["modes"]["mode_indices"][()]
    

for i in mode_indices:
    print(i)

[  2   0   0 -92]
[  2   0   0 -91]
[  2   0   0 -90]
[  2   0   0 -89]
[  2   0   0 -88]
[  2   0   0 -87]
[  2   0   0 -86]
[  2   0   0 -85]
[  2   0   0 -84]
[  2   0   0 -83]
[  2   0   0 -82]
[  2   0   0 -81]
[  2   0   0 -80]
[  2   0   0 -79]
[  2   0   0 -78]
[  2   0   0 -77]
[  2   0   0 -76]
[  2   0   0 -75]
[  2   0   0 -74]
[  2   0   0 -73]
[  2   0   0 -72]
[  2   0   0 -71]
[  2   0   0 -70]
[  2   0   0 -69]
[  2   0   0 -68]
[  2   0   0 -67]
[  2   0   0 -66]
[  2   0   0 -65]
[  2   0   0 -64]
[  2   0   0 -63]
[  2   0   0 -62]
[  2   0   0 -61]
[  2   0   0 -60]
[  2   0   0 -59]
[  2   0   0 -58]
[  2   0   0 -57]
[  2   0   0 -56]
[  2   0   0 -55]
[  2   0   0 -54]
[  2   0   0 -53]
[  2   0   0 -52]
[  2   0   0 -51]
[  2   0   0 -50]
[  2   0   0 -49]
[  2   0   0 -48]
[  2   0   0 -47]
[  2   0   0 -46]
[  2   0   0 -45]
[  2   0   0 -44]
[  2   0   0 -43]
[  2   0   0 -42]
[  2   0   0 -41]
[  2   0   0 -40]
[  2   0   0 -39]
[  2   0   0 -38]
[  2   0  

In [21]:

filename = (
    "ZNAmps_l10_m10_n92__extremal.h5" 
)


file_path = get_file_manager().get_file(filename)

with h5py.File(file_path, "r") as f:
    mode_indices = f["modes"]["mode_indices"][()]
    print(list(f.keys()))
    print(list(f["regionA"].keys()))
    coeffs= f["regionA"]["CoeffsRegionA"][()]
    params = f["regionA"]["ParamsRegionA"][()]
   
print(np.shape(coeffs),np.shape(mode_indices))
    

mode_indices
modemax = np.max(mode_indices, axis=0)

lmax = modemax[0]
mmax = modemax[1]

# total number of modes in the model
num_modes = len(mode_indices)
num_stored_modes = num_modes
num_teuk_modes =num_modes

for (i,j) in zip(mode_indices, coeffs[0,:,:,0]):
    print(i,j)

['metadata', 'modes', 'regionA']
['CoeffsRegionA', 'ParamsRegionA', 'u_knots', 'w_knots', 'z_knots']
(17, 6791, 2, 289) (6791, 4)
[  2   0   0 -92] [0. 0.]
[  2   0   0 -91] [0. 0.]
[  2   0   0 -90] [0. 0.]
[  2   0   0 -89] [0. 0.]
[  2   0   0 -88] [0. 0.]
[  2   0   0 -87] [0. 0.]
[  2   0   0 -86] [0. 0.]
[  2   0   0 -85] [0. 0.]
[  2   0   0 -84] [0. 0.]
[  2   0   0 -83] [0. 0.]
[  2   0   0 -82] [0. 0.]
[  2   0   0 -81] [0. 0.]
[  2   0   0 -80] [0. 0.]
[  2   0   0 -79] [0. 0.]
[  2   0   0 -78] [0. 0.]
[  2   0   0 -77] [0. 0.]
[  2   0   0 -76] [0. 0.]
[  2   0   0 -75] [0. 0.]
[  2   0   0 -74] [0. 0.]
[  2   0   0 -73] [0. 0.]
[  2   0   0 -72] [0. 0.]
[  2   0   0 -71] [0. 0.]
[  2   0   0 -70] [0. 0.]
[  2   0   0 -69] [0. 0.]
[  2   0   0 -68] [0. 0.]
[  2   0   0 -67] [0. 0.]
[  2   0   0 -66] [0. 0.]
[  2   0   0 -65] [0. 0.]
[  2   0   0 -64] [0. 0.]
[  2   0   0 -63] [0. 0.]
[  2   0   0 -62] [0. 0.]
[  2   0   0 -61] [0. 0.]
[  2   0   0 -60] [0. 0.]
[  2   0   0

In [25]:
np.max(coeffs[0,:,:,0])

np.float64(0.5538402406291643)

In [24]:
params

array([[[[ 0.99      ,  1.46449794,  0.        ],
         [ 0.99762863,  1.26323476,  0.        ],
         [ 0.99943766,  1.15659145,  0.        ],
         ...,
         [ 1.        ,  1.01041449,  0.        ],
         [ 1.        ,  1.01025652,  0.        ],
         [ 1.        ,  1.01015875,  0.        ]],

        [[ 0.99      ,  1.4698972 ,  0.        ],
         [ 0.99762863,  1.26863403,  0.        ],
         [ 0.99943766,  1.16199071,  0.        ],
         ...,
         [ 1.        ,  1.01581375,  0.        ],
         [ 1.        ,  1.01565579,  0.        ],
         [ 1.        ,  1.01555802,  0.        ]],

        [[ 0.99      ,  1.47821168,  0.        ],
         [ 0.99762863,  1.2769485 ,  0.        ],
         [ 0.99943766,  1.17030518,  0.        ],
         ...,
         [ 1.        ,  1.02412822,  0.        ],
         [ 1.        ,  1.02397026,  0.        ],
         [ 1.        ,  1.02387249,  0.        ]],

        ...,

        [[ 0.99      ,  5.67146297,  0

In [83]:
xp=np

filename = (
    "ZNAmps_l10_m10_n92__extremal.h5" 
)


file_path = get_file_manager().get_file(filename)

with h5py.File(file_path, "r") as f:
    mode_indices = f["modes"]["mode_indices"][()]

mode_indices
modemax = np.max(mode_indices, axis=0)
modemin = np.min(mode_indices, axis=0)#############

print(modemax)###########
print(modemin)###########

lmax = modemax[0]
mmax = modemax[1]

# total number of modes in the model
num_modes = len(mode_indices)
num_stored_modes = num_modes
num_teuk_modes =num_modes
m0mask = np.array(
    [
        mode[1] == 0
        for mode in mode_indices
    ]
)
m0sort = m0sort = xp.concatenate(
    [
        xp.arange(num_stored_modes)[m0mask],
        xp.arange(num_stored_modes)[~m0mask],
    ]
)
md = xp.asarray(mode_indices).T[:, m0sort].astype(xp.int32)
mode_arr_no_mask = md.T

print(np.shape(mode_arr_no_mask))
#for i in mode_arr_no_mask:
#    print(mode_arr_no_mask)###############################################

l_arr_no_mask =mode_arr_no_mask[:, 0]
m_arr_no_mask = mode_arr_no_mask[:, 1]
m0mask = m_arr_no_mask != 0

num_m_zero_up = len(m_arr_no_mask)

# number of m == 0
num_m0 = len(xp.arange(num_stored_modes)[m0mask])

# number of m > 0
num_m_1_up = num_m_zero_up - num_m0

mode_sign = [1] * len(md)
mode_sign[1] = -1

mode_arr = xp.asarray(
    [xp.concatenate([mode, sign*mode[m0mask]]) for mode, sign in zip(md, mode_sign)]
).T

l_arr = mode_arr[:, 0]
m_arr = mode_arr[:, 1]

# mask for m >= 0
m_zero_up_mask = m_arr >= 0

# find unique sets of (l,m)
# create inverse array to build full (l,m,n) from unique l and m
# also adjust for cupy

temp, inverse_lm = np.unique(
    np.asarray([l_arr, m_arr]).T, axis=0, return_inverse=True
)

# unique values of l and m
unique_l, unique_m = xp.asarray(temp).T
unique_l = unique_l
unique_m = unique_m

# number of unique values
num_unique_lm = len(unique_l)

# TODO make this more efficient
# mode indices for all positive m-modes
mode_indices = xp.linspace(
    0, num_stored_modes - 1, num_stored_modes, dtype=int
)

    # creates special maps to the modes
index_map_m_positive = {}
index_map_m_negative = {}
special_index_map = {}  # maps the minus m values to positive m

special_index_shape = modemax.copy()

print(special_index_shape)###########

special_index_shape[:2] += 1
special_index_shape[2:] = special_index_shape[2:] * 3 + 1

print(special_index_shape)###########

index_map_m_positive_arr = (
    xp.zeros(
        tuple(special_index_shape),
        dtype=xp.int32,
    )
    - 1
)
index_map_m_negative_arr = (
    xp.zeros(
        tuple(special_index_shape),
        dtype=xp.int32,
    )
    - 1
)
special_index_map_arr = (
    xp.zeros(
        tuple(special_index_shape),
        dtype=xp.int32,
    )
    - 1
)

for i, mode in enumerate(mode_arr_no_mask):
    try:
        mode = mode.get() # get the mode values if using cupy
    except AttributeError:
        pass
   # print(i,tuple(mode))

    # regular index to mode tuple
    index_map_m_positive[tuple(mode)] = i
    index_map_m_positive_arr[tuple(mode)] = i

[10 10  0 92]
[   2    0    0 -247]
(6791, 4)
[10 10  0 92]
[ 11  11   1 277]


In [82]:
for i in mode_arr_no_mask[:,3]:
    if i <-246 or i>90:
        print(i)

91
92
-247


In [56]:
index_map_m_negative_arr = (
    xp.zeros(
        tuple(special_index_shape),
        dtype=xp.int32,
    )
    - 10
)

In [64]:
modemax

array([10, 10,  0, 92])

In [2]:
AmpInterpKerrEccEq_nex().get_amplitudes(np.array([0.99]),np.array([6]),np.array([0.2]),np.array([1]))

array([[ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j, ...,
        -8.67746996e-30+3.08148791e-30j,  4.73316543e-30+5.12759588e-30j,
         3.94430453e-31+1.97215226e-31j]], shape=(1, 6791))

In [2]:
AmpInterpKerrEccEq().get_amplitudes(np.array([0.99]),np.array([6]),np.array([0.2]),np.array([1]))

Output()

KeyboardInterrupt: 

In [37]:
filename = (
    "ZNAmps_l10_m10_n92__extremal.h5" 
)


file_path = get_file_manager().get_file(filename)

with h5py.File(file_path, "r") as f:
    mode_indices = f["modes"]["mode_indices"][()]
    for i in mode_indices:
        print(i)



with h5py.File(file_path, "r") as f:
    regionA = f["regionA"]
    coeffsA = regionA["CoeffsRegionA"][()]
    w_knots = regionA["w_knots"][()]
    u_knots = regionA["u_knots"][()]
    z_knots = regionA["z_knots"][()]
    # paramsA = regionA["ParamsRegionA"][()]

    z_knots = z_knots
    coeffsA = coeffsA


[  2   0   0 -92]
[  2   0   0 -91]
[  2   0   0 -90]
[  2   0   0 -89]
[  2   0   0 -88]
[  2   0   0 -87]
[  2   0   0 -86]
[  2   0   0 -85]
[  2   0   0 -84]
[  2   0   0 -83]
[  2   0   0 -82]
[  2   0   0 -81]
[  2   0   0 -80]
[  2   0   0 -79]
[  2   0   0 -78]
[  2   0   0 -77]
[  2   0   0 -76]
[  2   0   0 -75]
[  2   0   0 -74]
[  2   0   0 -73]
[  2   0   0 -72]
[  2   0   0 -71]
[  2   0   0 -70]
[  2   0   0 -69]
[  2   0   0 -68]
[  2   0   0 -67]
[  2   0   0 -66]
[  2   0   0 -65]
[  2   0   0 -64]
[  2   0   0 -63]
[  2   0   0 -62]
[  2   0   0 -61]
[  2   0   0 -60]
[  2   0   0 -59]
[  2   0   0 -58]
[  2   0   0 -57]
[  2   0   0 -56]
[  2   0   0 -55]
[  2   0   0 -54]
[  2   0   0 -53]
[  2   0   0 -52]
[  2   0   0 -51]
[  2   0   0 -50]
[  2   0   0 -49]
[  2   0   0 -48]
[  2   0   0 -47]
[  2   0   0 -46]
[  2   0   0 -45]
[  2   0   0 -44]
[  2   0   0 -43]
[  2   0   0 -42]
[  2   0   0 -41]
[  2   0   0 -40]
[  2   0   0 -39]
[  2   0   0 -38]
[  2   0  

In [32]:
coeffsA

array([[[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

        [[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

        [[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

        ...,

        [[ 4.03150719e-44, -2.78333961e-41, -2.73965521e-41, ...,
           3.43448936e-09, -8.31997619e-09, -1.76608945e-09],
         [ 2.56141859e-44, -1.28152322e-40,  1.31254000e-41, ...,
          -1.13190

In [38]:
np.max(mode_indices, axis=0)

array([10, 10,  0, 92])